### ISSUE TITLE
pyright and ms-python simultaneously?

### ISSUE THREAD

**Issue by danilevy1212** [emacs-lsp/lsp-pyright#15]
Hi, I'm trying to decide between using this language server or the ms-python server, when I realized that vscode seems to be using both simultaneously to complement each other, since pyright as I understand it's just type checker.

Is this possible in emacs as well? How would someone set it up?

**Comment by seagle0128** [comment]
Why not try lsp-pyright? You will know that's what you exactly want 😄

**Comment by danilevy1212** [comment]
Yes, I ve furthered played around with pyright and I have found that I don't miss the alternatives.
