### ISSUE TITLE
Inherited class fields and function arguments does not autocomplete

### ISSUE THREAD

**Issue by KaratasFurkan** [emacs-lsp/lsp-pyright#17]
Hi, thanks for pyright integration first of all. It is super fast but does not autocomplete inherited class fields and function arguments.
For example:
```python
# in some file which imported
class Emacs:
    version = 26

# in current file
class Emacs27(Emacs):
    ver*
```
it does not suggest "version" here.

Is it about pyright or lsp-pyright?

**Comment by seagle0128** [comment]
I believe you will get the same results with VSCode. Shouldn't it be `Emacs.version`?

**Comment by KaratasFurkan** [comment]
Yes you are right. I tried with vscode and got the same result, the problem is about pyright then. Thanks.

**Comment by seagle0128** [comment]
Please file an issue for pyright.

**Comment by KaratasFurkan** [comment]
https://github.com/microsoft/pyright/issues/962 i did.
