### ISSUE TITLE
Server only in multi-root mode despite custom variable setting

### ISSUE THREAD

**Issue by jsigman** [emacs-lsp/lsp-pyright#19]
I updated both `lsp-mode` and `lsp-pyright` today.

Now, I am  getting the same issue as in https://github.com/emacs-lsp/lsp-pyright/issues/6 despite setting the customization variable `lsp-pyright-multi-root` to `nil`.

Any thoughts on how to debug? This is quite odd. I had confirmed before that https://github.com/emacs-lsp/lsp-pyright/issues/6 was fixed, but now it has resumed to its old behavior.

**Comment by jsigman** [comment]
Appears to be this:

https://github.com/emacs-lsp/lsp-pyright/blob/master/lsp-pyright.el#L218

```elisp
:multi-root (lambda () lsp-pyright-multi-root)
```

should be:

```elisp
:multi-root lsp-pyright-multi-root
```

**Comment by liebkne** [comment]
Setting `lsp-pyright-multi-root` to nil does not help here. I always got messages like

```
LSP :: pyright:60685 initialized successfully in folders: (/path/1 /path/2 ..... lots of paths)
```

even I'd like to open single file of single project. Then `pyright` takes some time and 100% CPU to analysis these folders.

- LSP version: master
- pyright version: 1.1.136
- emacs version: GNU Emacs 27.2 (build 1, x86_64-apple-darwin20.3.0, Carbon Version 164 AppKit 2022.3) of 2021-04-02

**Comment by aagaard** [comment]
I have the same issue with pyright. It is initializing in a lots of folders and then uses 100% CPU to analysis these folders.

**Comment by seagle0128** [comment]
@liebkne @aagaard I think you misunderstood `lsp-pyright-multi-root`:  whether the client supports multi root workspace. If you don't want `pyright` to index all lib folders, you should see the settings of `pyright` itself: https://github.com/microsoft/pyright/blob/main/docs/settings.md, e.g. `python.analysis.useLibraryCodeForTypes`, `python.analysis.extraPaths`, etc.

Also, you can test the same source codes with `pyright` in VSCode, to check the settings and behaviors.

**Comment by KevOrr** [comment]
@seagle0128 isn't the point of `lsp-pyright-multi-root nil` to run one pyright server for each project/root that's opened? I'm seeing the same behavior as described above, where regardless of the value of `lsp-pyright-multi-root`, a single pyright server is initialized in all of the folders listed in `(gethash 'pyright (lsp-session-server-id->folders (lsp-session)))`

**Comment by seagle0128** [comment]
@KevOrr Hmm, I think @yyoncho could explain this. It's the core functionality from lsp-mode.
@yyoncho Could you please take a look?
