### ISSUE TITLE
Docstrings

### ISSUE THREAD

**Issue by r-zip** [emacs-lsp/lsp-pyright#20]
The documentation that `lsp-pyright` returns appears to be minimal (e.g., only function signatures rather than signatures and docstrings). However, the VSCode `pyright` client can show docstrings too. Is it possible to show docstrings in addition to the minimal hover info currently provided?

EDIT: It appears I was using Pylance and not Pyright in VS Code, which I just realized is not open source. Closing this issue.

**Comment by jul1u5** [comment]
I've also encountered the same issue. I checked [coc-pyright](https://github.com/fannheyward/coc-pyright) and they have documentation working. So, I think this should be reopened.
