### ISSUE TITLE
[RFE] command to restart a pyright server

### ISSUE THREAD

**Issue by suvayu** [emacs-lsp/lsp-pyright#23]
Sometimes I see the pyright session is stale, and doesn't pick up changes like newly added dependencies.  Typically this happens when I'm changing/enabling virtual environments for some reason (in the same file).  Presently I do it by manually editing `venvPath` and `venv` in `pyrightconfig.json`.

It would be great if we could have a command to restart the pyright session to pickup these changes.  At the moment I have to restart emacs.

**Comment by seagle0128** [comment]
Does `lsp-restart-workspace` work for you?

**Comment by suvayu** [comment]
Thanks! I tried `lsp-restart-workspace`, it does exactly what I was looking for.  Sorry about the noise.
