### ISSUE TITLE
Support `poetry run pyright-langserver`

### ISSUE THREAD

**Issue by galagora** [emacs-lsp/lsp-pyright#24]
Currently, when using Poetry with a local venv, you have to create a `.dir-locals.el` file containing something like:
```emacs
((python-mode . ((lsp-pyright-venv-path . "/home/user/project/.venv")))))
```
It would be great if we were able to configure the Pyright command, or at least set an option to run it through Poetry. I tried this (somewhat hacky) solution:
```emacs
(eval-after-load 'lsp-clients
  '(progn
     (lsp-dependency 'pyright (:system ,(executable-find "poetry")))
     ))

(after! lsp-pyright
  (setq lsp-pyright-langserver-command-args "run pyright-langserver --stdio"))
```
But it didn't work ("Unable to find installed server...").

**Comment by zeronone** [comment]
How about using `direnv` (in use `direnv-mode` in emacs)?

**Comment by galagora** [comment]
I ended up just defining a shell alias to populate the `.dir-locals.el` file and initialize a Poetry project. Feel free to close this issue.
