### ISSUE TITLE
Is setting file watchers on `site-packages` necessary?

### ISSUE THREAD

**Issue by rtpg** [emacs-lsp/lsp-pyright#25]
I have some pretty big projects, with a lot of dependencies. Right now I just let file watches happen on everything, which causes the LSP bootup to be pretty slow.

But is there a way to just indicate to the plugin to _just_ look at the "main" project directory? I don't really need the server to be responsive to dependency changes, but I do want it to respond quickly to main project file changes.

(aside: do I even need file watching in general if nothing outside of Emacs is touching the files? Like does saving already "refresh the data" so to speak?)

Thanks for the effort put into this plugin!

**Comment by seagle0128** [comment]
I think you need to read https://github.com/microsoft/pyright/blob/master/docs/configuration.md. `exclude` or `ignore` may be helpful in this case.

**Comment by zeronone** [comment]
You can check the `lsp-log` to see which files are being watched.
You can also disable file-watching with configuring `lsp-enable-file-watchers` variable.

**Comment by rtpg** [comment]
Ah, thank you, I was under the impression this was configured in the plugin given that I was being prompted in emacs in a certain way. I will read up on that.
