### ISSUE TITLE
[Question] Is it possible to custom `python.analysis.diagnosticSeverityOverrides`

### ISSUE THREAD

**Issue by nasyxx** [emacs-lsp/lsp-pyright#27]
Hi,

Is it possible to custom `python.analysis.diagnosticSeverityOverrides` ?

https://github.com/microsoft/pyright/blob/master/docs/settings.md

https://github.com/microsoft/pyright/blob/master/docs/configuration.md#type-check-diagnostics-settings

I have tried to add one in `lsp-register-custom-settings` like:

`("python.analysis.diagnosticSeverityOverrides.reportUnusedFunction" "warning")`

but not work as expected.

**Comment by seagle0128** [comment]
No, you should configure it in pyright config file `pyrightconfig.json`.

**Comment by nasyxx** [comment]
> No, you should configure it in pyright config file `pyrightconfig.json`.

I see.  I'm looking for a method that works with all projects.
