### ISSUE TITLE
Update website with Pyright info

### ISSUE THREAD

**Issue by leungbk** [emacs-lsp/lsp-pyright#3]
https://emacs-lsp.github.io/lsp-mode/

**Comment by zeronone** [comment]
Thanks will do it after submission to melpa is completed (#4 )

**Comment by seagle0128** [comment]
@leungbk Can you provide the guidance how to update the docs? Should we update https://github.com/emacs-lsp/lsp-mode/blob/master/docs/lsp-clients.json? I've created the doc for lsp-pyright: https://emacs-lsp.github.io/lsp-pyright/.

**Comment by leungbk** [comment]
@seagle0128 I have never updated the docs myself before. But the commits I've seen that do have updated `lsp-clients.json` as you said as well as `mkdocs.yml`, following https://github.com/emacs-lsp/lsp-mode/blob/79f147418f5f7f361c2664bee696c2da481a04ca/docs/page/adding-new-language.md#L69.

**Comment by seagle0128** [comment]
PR https://github.com/emacs-lsp/lsp-mode/pull/2074 has been submitted..

**Comment by leungbk** [comment]
Nice, I see it from the main Emacs LSP page. Thanks!
