### ISSUE TITLE
lsp method error

### ISSUE THREAD

**Issue by alienzj** [emacs-lsp/lsp-pyright#31]
Hi, I use doom-emacs and pyright.

I encountered the following error today:

```
Error runnint timer 'lsp--on-idle': (error "The connected server(s) does not support method textDocument/documentHighlight.
```

Any help ? Thanks : D

**Comment by seagle0128** [comment]
Try this:
1. Upgrade `pyright` through `lsp-update-server`.
1. Or disable `lsp-enable-symbol-highlighting`.
1. Or ignore it.

**Comment by alienzj** [comment]
After updating pyright, the error disappeared.
Thanks.
