### ISSUE TITLE
Cannot start pyright server from emacs

### ISSUE THREAD

**Issue by chshr** [emacs-lsp/lsp-pyright#34]
Cannot start pyright server from lsp-mode. In *pyright::stderr* buffer I am seeing "cannot find module 'worker_threads'" error. Found a few posts online where people had similar error when using older versions of node (<12). I had old node but updated it with nvm to 14.15.2. I can start pyright just from bash (Ubuntu 20.04 in WSL2), but from emacs I always get the error. How do I troubleshoot it?
Tried emacs 26.3 and 27.1 with Spacemacs.

**Comment by chshr** [comment]
Ok, from inside emacs when I run shell command "node --version", the version is v10.19.0.
However, nvm outside emacs does not even recognize this version as installed, so I am unable to uninstall it that way.
How do I change which version of node lsp-pyright uses?

**Comment by seagle0128** [comment]
Did you see [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell)?

**Comment by chshr** [comment]
> Did you see [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell)?

I've tried and it worked like a charm. Problem solved, thanks.

**Comment by cactail** [comment]
> > Did you see [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell)?
> 
> I've tried and it worked like a charm. Problem solved, thanks.

Can you share what you did?

**Comment by chshr** [comment]
> Can you share what you did?

Installed exec-path-from-shell package, that's it.
