### ISSUE TITLE
How to suppress "XXX is not accessed"

### ISSUE THREAD

**Issue by byulparan** [emacs-lsp/lsp-pyright#39]
<img width="687" alt="스크린샷 2021-03-03 오후 9 24 44" src="https://user-images.githubusercontent.com/459573/109805658-132b1b80-7c67-11eb-8f34-ffeee0c78d5f.png">

I created `pyrightconfig.json` 

```javascript
{
    "reportUnusedVariable" : "none",
    "reportUnusedImport": "none",
    "reportUnusedFunction": "none",
}
``` 

but It's not effective.

when I run `pyright` in Terminal, It's avoid.
<img width="587" alt="스크린샷 2021-03-03 오후 9 30 40" src="https://user-images.githubusercontent.com/459573/109806169-b8de8a80-7c67-11eb-8fc1-ead3b7c8e9bc.png">

How to I get just warning / error report. I don't want get Info-level report(green face).

**Comment by tshu-w** [comment]
@byulparan The default of "reportUnusedVariable" is "none", see [here](https://github.com/microsoft/pyright/blob/main/docs/configuration.md#diagnostic-rule-defaults). maybe related: https://github.com/microsoft/pyright/issues/1118

**Comment by tshu-w** [comment]
@seagle0128 or maybe we can add an option to disable hint.

**Comment by byulparan** [comment]
hmm....is it can't resolve?

**Comment by byulparan** [comment]
It seems not `lsp-pyright` problem. I resolved it via `lsp-diagnostic-filter`. 
Thanks.

**Comment by tshu-w** [comment]
@byulparan can you share how to set `lsp-diagnostic-filter`, thx

**Comment by byulparan** [comment]
It just cut tag(unnecessary/deprecated) diagnostic.

```emacs-lisp
(setf lsp-diagnostic-filter (lambda (param work)
			      (puthash "diagnostics" 
				       (cl-remove-if (lambda (diag) (gethash "tags" diag))
						     (gethash "diagnostics" param))
				       param)
			      param))
```
