### ISSUE TITLE
Can not import cv2 correctly

### ISSUE THREAD

**Issue by binwan-dev** [emacs-lsp/lsp-pyright#41]
I'm use pyrightconfig json file and install cv2. 
Can't prompt correctly for cv2.imread or cv2.imwrite
Sorry, my english is not good.
我已经安装了cv2 包 在 test 环境下，并且使用了pyrightconfig.json 文件。
现在问题是无法正常提示cv2的候选项，例如 imread imwrite,这些都无法正常提示。
不过其他包（tensorflow numpy）都能正常提示
![image](https://user-images.githubusercontent.com/45676208/112443634-27ef6080-8d88-11eb-9cfc-d7ab611d79f3.png)

this is my pyrightconfig.json
![image](https://user-images.githubusercontent.com/45676208/112444053-96342300-8d88-11eb-952e-639388232088.png)

this is lsp-log
![image](https://user-images.githubusercontent.com/45676208/112444108-a8ae5c80-8d88-11eb-8326-03d86e504dec.png)

**Comment by Blade6570** [comment]
Issue is here: https://github.com/microsoft/pylance-release/issues/138

**Comment by steepestascent** [comment]
I needed to modify the `stubgen` command for this to work.

```
cd {to your cv2 directory}
stubgen -m cv2 -o .
mv cv2.pyi __init__.pyi
```

`M-x lsp-restart-workspace`

**Comment by binwan-dev** [comment]
It work, Thanks! I'll close this issue
