### ISSUE TITLE
Unable to display docstring (this seems not be a bug)

### ISSUE THREAD

**Issue by purofle** [emacs-lsp/lsp-pyright#44]
Many modules use docstring, which makes the code easier to read

**Comment by SreenivasVRao** [comment]
Agreed - same as #20 - no docstrings is a deal breaker for adopting lsp-pyright... is this a "newbie" elisp task? I might be able to work on this.

**Comment by seagle0128** [comment]
You should file an issue for `pyright`. VSCode with pyright extension has the same behavior.

**Comment by dsyzling** [comment]
I narrowed this down to lsp-ui-doc--render-buffer and the following lines:
```elisp
(let ((fill-column (- lsp-ui-doc-max-width 5)))
  (fill-region (point-min) (point-max)))
```

Removing these lines correctly renders the newlines and the horizontal rule. There's an open issue with some people seeing issues with HRs in markdown and I've added to the discussion over on lsp-ui. If you turn on lsp-mode tracing you can see the markdown returned for the textDocument/hover and you'll see that newlines are returned correctly along with other formatting. Now there appears to be some confusion over whether there should be some combination of spaces at the end of a line, \ or two newlines but I think markdown mode gfm-view-mode etc. should render newlines. The Scala metals server also returns newlines and I'm seeing similar formatting issues under metals in my system. 

The lsp-ui PR is here: https://github.com/emacs-lsp/lsp-ui/issues/611. It's not quite the same but there's similar related issues.

**Comment by dsyzling** [comment]
I think this PR can be closed, it appears to be resolved by a Wrap Paragraph fix made over in lsp-ui: https://github.com/emacs-lsp/lsp-ui/pull/643

**Comment by djr7C4** [comment]
This issue seems to be occuring once again with the lastest version of lsp-mode from MELPA (20231018.1322).
