### ISSUE TITLE
Unable to install lsp-pyright from melpa

### ISSUE THREAD

**Issue by rlvoyer** [emacs-lsp/lsp-pyright#53]
I am running emacs 27.2 on a Mac running Big Sur. I am unable to install lsp-pyright from melpa. I cannot get it to show up in the package list `package-list-packages` and I cannot install it directly via `package-install`. Is this because it depends on emacs 26? Is the dependency on emacs 26 a hard dependency?

**Comment by rlvoyer** [comment]
I was able to install it manually by downloading lsp-pyright.el and adding it to my load-path, but it would be nice if I could use `package` to install it from melpa.

**Comment by jcs090218** [comment]
lsp-pyright is on MELPA, see https://melpa.org/#/lsp-pyright.

Maybe it's already installed yet you didn't see it? 😕

**Comment by seagle0128** [comment]
I can confirm `lsp-pyright` is able to be installed on Emacs 26.x, 27.x and 28.x. I am using macOS Big Sur. Please delete and reinstall.

**Comment by rlvoyer** [comment]
Hi there. Thanks for taking a look. I think the issue was that I was only looking at melpa-stable.
