### ISSUE TITLE
Disable tab error

### ISSUE THREAD

**Issue by ahoodatheguy** [emacs-lsp/lsp-pyright#56]
I edit my python code with tabs instead of spaces, I know that PEP 8 says to use spaces, but I honestly hate using them and I want my tab key to input... well tabs.
Anyway I keep getting errors using pyright saying ``indentation contains tabs`` and I can't seem to get rid of them, has anyone else solved this issue?

**Comment by seagle0128** [comment]
I am curious why don't you use `(setq-default indent-tabs-mode nil)`?

**Comment by ahoodatheguy** [comment]
> I am curious why don't you use `(setq-default indent-tabs-mode nil)`?

What like this?

```
(add-hook 'python-mode-hook
  (lambda ()
    (setq indent-tabs-mode t)
    (setq python-indent 4)
    (setq tab-width 4)))
```

Sorry if i'm asking a dumb question i'm a bit new to Emacs and can't find a fix to this issue anywhere.

**Comment by seagle0128** [comment]
> > I am curious why don't you use `(setq-default indent-tabs-mode nil)`?
> 
> What like this?
> 
> ```
> (add-hook 'python-mode-hook
>   (lambda ()
>     (setq indent-tabs-mode t)
>     (setq python-indent 4)
>     (setq tab-width 4)))
> ```
> 
> Sorry if i'm asking a dumb question i'm a bit new to Emacs and can't find a fix to this issue anywhere.

Should be  `(setq indent-tabs-mode nil)`.
