### ISSUE TITLE
Server starts up with multiple workspace folders with no instruction to do so

### ISSUE THREAD

**Issue by jsigman** [emacs-lsp/lsp-pyright#6]
When I start up a new project with pyright, the log shows that "workspaceFolders" in the log has many entries. I'm not sure how these are being set but it slows down the project with file watchers.

Any thoughts?  It looks like these are every paths to every python project I've ever run this in. Could it be reading my projectile bookmarks?

<img width="566" alt="Screen Shot 2020-07-28 at 10 34 45 PM" src="https://user-images.githubusercontent.com/2373529/88750127-d9b78e00-d122-11ea-9067-dad6745d06de.png">

**Comment by zeronone** [comment]
`lsp-pyright` doesn't have any workspace detection logic. It only have some code to detect the Python interpreter. Workspace detection is done by `lsp-mode`. 

Maybe `lsp-mode` is detecting some top folder (i.e: `~/repos/*`) as the root which has all your repositories. 
What is your `lsp-auto-guess-root` value?

**Comment by jsigman** [comment]
`lsp-auto-guess-root` is nil, but turning this on changes nothing.

`(lsp--suggest-project-root)` returns the correct folder, but only one folder...

**Comment by yyoncho** [comment]
This is the expected behaviour when a server is multiroot.

**Comment by jsigman** [comment]
So it is a pyright server setting that is making it multiroot, then? It's not in the Elise config

**Comment by yyoncho** [comment]
@jsigman it is a server feature which is enabled on client-side. Technically it can be disabled on emacs side. We do that for lsp-solargraph.el for example.

**Comment by jsigman** [comment]
Yup I see where you are doing that. I'll add a config option and test that out a little bit on my end. At least for me, this multi-root aspect of the server is causing problems.

Thank you

**Comment by zeronone** [comment]
I created a PR (#8) to make it configurable. Please let me know if it works for you.

**Comment by jsigman** [comment]
addressed by https://github.com/emacs-lsp/lsp-pyright/pull/8
