### ISSUE TITLE
Can lsp-pyright use python-lsp-server as an alternative backend?

### ISSUE THREAD

**Issue by hongyi-zhao** [emacs-lsp/lsp-pyright#61]
I noticed that [python-lsp-server](https://github.com/python-lsp/python-lsp-server) is a Python 3.6+ implementation of the [Language Server Protocol](https://github.com/Microsoft/language-server-protocol). I want to know if `lsp-pyright` can use `python-lsp-server` as an alternative backend?

Regards,
HZ

**Comment by seagle0128** [comment]
No. `lsp-pyls` and `lsp-pylsp` are built in `lsp-mode`.

**Comment by hongyi-zhao** [comment]
What's the difference between `lsp-pyls` and `lsp-pylsp`, and which is for `python-lsp-server`?
