### ISSUE TITLE
How specify Python interpreter with elisp

### ISSUE THREAD

**Issue by dev590t** [emacs-lsp/lsp-pyright#67]
I'm trying to integrate lsp-pyright with PDM python package manager and doom-emacs. But I fails to make pyright to use my PDM python interpreter. It still use my system interpreter. 

I have tried to use `lsp-pyright-auto-search-paths` and `lsp-pyright-venv-path` to specify python interpreter, but that doesn't work
```
(defun pdm-get-python-executable (&optional dir)
    (let ((pdm-get-python-cmd "pdm info --python"))
      (string-trim
       (shell-command-to-string
        (if dir
            (concat "cd "
                    dir
                    " && "
                    pdm-get-python-cmd)
          pdm-get-python-cmd)))))

(defun pdm-get-packages-path (&optional dir)
  (let ((pdm-get-packages-cmd "pdm run bash -c 'printenv PEP582_PACKAGES'"))
    (concat (string-trim
             (shell-command-to-string
              (if dir
                  (concat "cd "
                          dir
                          " && "
                          pdm-get-packages-cmd)
                pdm-get-packages-cmd)))
            "/lib")))

(add-hook! python-mode
  (setq lsp-pyright-extra-paths (vector (pdm-get-packages-path)))
  (setq lsp-pyright-auto-search-paths (pdm-get-python-executable))
  (setq lsp-pyright-venv-path (pdm-get-python-executable))
  (require 'lsp-pyright)
  (lsp)) ; or lsp-deferred
```

**Comment by dev590t** [comment]
I use doom emacs. It use a different mecanism to add package than classic emacs. 

After reconfigure `~/.doom.d/init.el` with `(python +lsp +pyright +pyenv +poetry +cython) `. And install the packages in .venv. lsp-pyright can automatically find the package and the interpreter in .venv without any additional configuration.

Thanks you for your answer

**Comment by worldofgeese** [comment]
@dev590t and others who stumble upon this, @zealinux's code sample is correct for any Emacs distro other than Doom. To make it compatible with Doom, one just needs to add a `!` after `use-package`:
```elisp
(use-package lsp-pyright
  :ensure t
  :hook (python-mode . (lambda ()
                         (setq lsp-pyright-extra-paths (vector (pdm-get-packages-path)))
                         (setq lsp-pyright-auto-search-paths (pdm-get-python-executable))
                         (setq lsp-pyright-venv-path (pdm-get-python-executable))
                          (require 'lsp-pyright)
                          (lsp)))) 
```

@frostming, @zealinux's solution is a great code sample on getting PDM working with Pyright in Emacs.

Many thanks to @zealinux for his generous offering :heart:
