### ISSUE TITLE
lsp-mode doesn't seem to try to load pyright when opening python file

### ISSUE THREAD

**Issue by CamJN** [emacs-lsp/lsp-pyright#80]
I have the following in my `~/.emacs.d/init.el`:
```
(require 'lsp-pyright)
(with-eval-after-load 'lsp-mode
  (add-hook 'python-mode-hook #'lsp-deferred)
)
```
and when I open a python file I see the following in the minibuffer:
`Unable to find installed server supporting this file. The following servers could be installed automatically: `
and the lsp-log says:
```
Command "pyls" is not present on the path.
Command "pylsp" is not present on the path.
```

Which seems like emacs isn't even trying to use pyright. 

I have `lsp-pyright` `20221201.1501` and `lsp-mode` `20230126.1057` installed.

**Comment by rgri** [comment]
Do you happen to be running DOOM emacs?

**Comment by CamJN** [comment]
Nope, my own artisanal emacs config.

**Comment by CamJN** [comment]
`Command "ruff-lsp" is not present on the path.` has started to appear in the list but pyright still does not.

**Comment by CamJN** [comment]
Ok so it turns out that at least on macOS, this is completely broken unless you activate a venv in emacs in the python buffer before activating lsp-mode there. Otherwise, for some reason lsp-pyright cannot install pyright, and lsp-mode doesn't even know pyright is an language server for python. No idea why that is.
