### ISSUE TITLE
(🎁) Support basedpyright

### ISSUE THREAD

**Issue by KotlinIsland** [emacs-lsp/lsp-pyright#92]
Basedpyright is a Pyright fork with many improvements and new features

Link: https://github.com/DetachHead/basedpyright

I would be awesome if this project could support Basedpyright

**Comment by JohnDevlopment** [comment]
I tried using it but I got this error: `Unable to find installed server supporting this file. The following servers could be installed automatically:`

Previously, I had been using pyright, but I recently changed the option to use basedpyright, hence this error.

**Comment by seagle0128** [comment]
@JohnDevlopment You need to install `basedpyright` manually. See https://docs.basedpyright.com/#/installation.

**Comment by rirze** [comment]
I didn't see any documentation covering this, so I'm leaving a snippet for anyone figuring this out like I did:
```elisp

(use-package lsp-pyright
  :ensure t
  :custom
  (lsp-pyright-langserver-command "basedpyright")
  :hook (python-base-mode . (lambda ()
                              (require 'lsp-pyright)
                              (lsp))))  ; or lsp-deferred
```
