### ISSUE TITLE
lsp-pyright server crashes

### ISSUE THREAD

**Issue by andrewdoh** [emacs-lsp/lsp-pyright#93]
im not sure whats going on any help would be appreciated. im using a m2 mba on sonoma. message buffer returns the following:

LSP :: Connected to [pyright:55758/starting /Users/andrew][ruff-lsp:55759/starting /Users/andrew].
LSP :: pyright:55758 initialized successfully in folders: (/Users/andrew)
LSP :: ruff-lsp:55759 initialized successfully in folders: (/Users/andrew)
LSP :: pyright has exited (abort trap: 6)

**Comment by seagle0128** [comment]
Hey guys, try the `pyright` cli directly and you can get the direction.

**Comment by rpls** [comment]
Just running `pyright` in the project directory, it seems to scan only the project itself. I rolled back `lsp-{mode,ui,pyright}` to versions when I didn't have the problem, and the error persists. Not sure what else to check right now. I'm using Spacemacs, maybe it's some other side effect.

**Comment by seagle0128** [comment]
There are too many files and directories in HOME folder obviously. This case should be avoided.

**Comment by andrewdoh** [comment]
> I have the same problem. Tracked it down to `lsp-pyright` including the home folder, which causes pyright to scan everything in home and inevitably run out of memory.
> 
> ```
> LSP :: pyright:87121 initialized successfully in folders: (/Users/USERNAME /Volumes/projects/PROJECTFOLDER)
> ```
> 
> My quickfix right now is to create a `pyrightconfig.json` in the home folder with the following contents:
> 
> ```
> {
> 	"exclude": ["**"]
> }
> ```
> 
> I'm not sure why the home folder is added at all, but other `lsp` clients (e.g., `lsp-clangd`) don't do this, so I'm inclined to blame `lsp-pyright` or `pyright` itself.

thanks for the tip this helped alot.

**Comment by seagle0128** [comment]
So I am closing it...
